In [4]:
import numpy as np
import pandas as pd

In [14]:
arr = np.array([[1,2,3,4,5],[6,7,8,8,9]])
arr.sum(axis=0)
arr.sum(axis=1)
arr.mean(axis=0)

array([3.5, 4.5, 5.5, 6. , 7. ])

In [20]:
arr = np.array([10,20,30,4,5])
for i in arr:
    print(i)

[10 20 30  4  5]
[10 20 30  4  5]


In [24]:
arr[0]

array([10, 20, 30,  4,  5])

In [26]:
arr

array([[10, 20, 30,  4,  5],
       [10, 20, 30,  4,  5]])

# Mean

In [29]:
arr = np.array([10,20,30,4,5])
avg = np.average(arr,weights=[1,2,34,5,1])
print(avg)

25.46511627906977


# Median

In [32]:
arr = np.array([10,9,8,6,5])
np.median(arr)

8.0

# Mode

In [43]:
from collections import Counter
arr = np.array([1,1,1,2,5,1,1,12,3,2,2,2,4,3,2,1,1,2,33,2,3,1,1,2,23,5])

In [56]:
count = Counter(arr)
print(count)
count.most_common(1)   #1 defines the nth max occurance

Counter({1: 9, 2: 8, 3: 3, 5: 2, 12: 1, 4: 1, 33: 1, 23: 1})


[(1, 9)]

# Standard Deviation